
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Jun 21 19:23:38 CEST 2015
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MASMAS = 42;
  public static final int NOT_BOOL = 29;
  public static final int MENOSMENOS = 18;
  public static final int POR = 19;
  public static final int PUNTO_Y_COMA = 15;
  public static final int GE = 23;
  public static final int CONTINUE = 35;
  public static final int INT = 37;
  public static final int PORCEN = 12;
  public static final int FOR = 33;
  public static final int AND = 26;
  public static final int IGUAL = 13;
  public static final int LT = 22;
  public static final int LL_AP = 10;
  public static final int OR = 25;
  public static final int BOOL = 38;
  public static final int DIV = 20;
  public static final int C_CIERRE = 9;
  public static final int IF = 31;
  public static final int C_AP = 8;
  public static final int P_CIERRE = 7;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int LL_CIERRE = 11;
  public static final int RETURN = 34;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int COMA = 14;
  public static final int MENOS = 17;
  public static final int BREAK = 36;
  public static final int DIST_BOOL = 28;
  public static final int VOID = 39;
  public static final int ENT = 3;
  public static final int ELSE = 32;
  public static final int PUNTO = 41;
  public static final int IDEN = 2;
  public static final int WHILE = 30;
  public static final int P_AP = 6;
  public static final int IGUAL_BOOL = 27;
  public static final int FALSE = 5;
  public static final int STRUCT = 40;
  public static final int GT = 24;
  public static final int MAS = 16;
}

