package alex;

public enum ClaseLexica {
 IDEN, ENT, P_AP, P_CIERRE, C_AP, C_CIERRE, LL_AP, LL_CIERRE, PORCEN, 
 IGUAL, COMA, PUNTO_Y_COMA, MAS, MENOS, POR, DIV, LT, LE, GT, GE, EOF, OR, AND, 
 IGUAL_BOOL, DIST_BOOL, NOT_BOOL, MASMAS, MENOSMENOS, WHILE, IF, ELSE, FOR, 
 RETURN, CONST, CONTINUE, BREAK, INT, BOOL, VOID, STRUCT, TRUE, FALSE,
 PUNTO
}
